apiVersion: v1
kind: Service
metadata:
  labels:
    app: reverseproxy
  name: reverseproxy-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/reverseproxy-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: reverseproxy
    service: reverseproxy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
